In [1]:
import numpy as np

In [2]:
range(10)

range(0, 10)

In [3]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
list(range(3,10))#range can only take integer

[3, 4, 5, 6, 7, 8, 9]

In [7]:
list(range(3,10.5))

TypeError: 'float' object cannot be interpreted as an integer

In [11]:
np.arange(10) #arange can generate floating number

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(.5,10)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [13]:
np.arange(.0,10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [14]:
np.arange(5,-4,-1)

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3])

In [15]:
np.arange(5,-4,-0.5)

array([ 5. ,  4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ,
       -0.5, -1. , -1.5, -2. , -2.5, -3. , -3.5])

In [18]:
np.linspace(1,5,20) #it will generate 20 datasets between 1 to 5 with upper bound 5 and lower bound 1 included

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [19]:
list(np.linspace(1,5,20))

[1.0,
 1.2105263157894737,
 1.4210526315789473,
 1.631578947368421,
 1.8421052631578947,
 2.052631578947368,
 2.263157894736842,
 2.473684210526316,
 2.6842105263157894,
 2.894736842105263,
 3.1052631578947367,
 3.3157894736842106,
 3.526315789473684,
 3.7368421052631575,
 3.9473684210526314,
 4.157894736842105,
 4.368421052631579,
 4.578947368421052,
 4.789473684210526,
 5.0]

In [22]:
list(np.linspace(1,5,20,retstep=True))  #give jumpsize also in the end

[array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
        2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
        3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
        4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]),
 0.21052631578947367]

In [23]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [24]:
np.logspace(1,5,10)  #logrithmic of data base on upper and lowe bound values #Return numbers spaced evenly on a log scale.

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [25]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [26]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.zeros((3,5,2)) #it will generate 5x2 3 matrices

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [28]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [29]:
np.ones(3,4)

TypeError: Cannot interpret '4' as a data type

In [30]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [34]:
np.ones((3,4,2)) * 5

array([[[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]]])

In [35]:
#in case of numpy we have only zeros and ones

In [36]:
np.empty((2,3))

array([[4.81117707e-310, 0.00000000e+000, 1.88693414e+185],
       [2.59027906e-144, 1.16442250e-028, 9.44872517e-143]])

In [38]:
np.empty((3,3,3))

array([[[4.81117531e-310, 0.00000000e+000, 6.12933591e-310],
        [6.12933593e-310, 6.12933601e-310, 6.12933593e-310],
        [6.12933592e-310, 6.12933593e-310, 6.12933592e-310]],

       [[6.12933593e-310, 6.12933591e-310, 6.12933593e-310],
        [6.12933591e-310, 6.12933593e-310, 6.12933591e-310],
        [6.12933593e-310, 6.12933591e-310, 6.12933593e-310]],

       [[6.12933591e-310, 6.12933593e-310, 6.12933593e-310],
        [6.12933593e-310, 6.12933737e-310, 6.12933592e-310],
        [6.12933592e-310, 6.12933592e-310, 1.10670705e-321]]])

In [40]:
np.eye(4) #diagonal elements going to be 1 this matrices is called identity matrices

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
a = np.eye(4)

In [46]:
a.shape  #what is dimension of entire matrices

(4, 4)

In [47]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
a.size #size is gonna tell how many elements are available in your array

16

In [51]:
a.ndim #dimension of the array is given by ndim

2

In [53]:
a1 = np.random.randn((3,4))

TypeError: 'tuple' object cannot be interpreted as an integer

In [54]:
a1 = np.random.randn(3,4)

In [55]:
a1

array([[ 1.48523759,  0.13369167,  1.40268948, -0.84208133],
       [ 0.95077105, -0.23740909, -2.42230403,  0.85819974],
       [-0.57275571, -0.7028063 ,  0.38544657,  0.33469914]])

In [56]:
import pandas as pd

In [58]:
pd.DataFrame(a1)  #loc and ilocs can be used here

0         1         2         3
0  1.485238  0.133692  1.402689 -0.842081
1  0.950771 -0.237409 -2.422304  0.858200
2 -0.572756 -0.702806  0.385447  0.334699

In [59]:
a1

array([[ 1.48523759,  0.13369167,  1.40268948, -0.84208133],
       [ 0.95077105, -0.23740909, -2.42230403,  0.85819974],
       [-0.57275571, -0.7028063 ,  0.38544657,  0.33469914]])

In [61]:
a1[1,1]

-0.23740909204604196

In [62]:
a1[1],[1]

(array([ 0.95077105, -0.23740909, -2.42230403,  0.85819974]), [1])

In [63]:
a1[1][1]

-0.23740909204604196

In [65]:
a1[0:2 , 0:2]

array([[ 1.48523759,  0.13369167],
       [ 0.95077105, -0.23740909]])

In [71]:
a1[[0,1],[0,1]]

array([ 1.48523759, -0.23740909])

In [73]:
a1([0,1],[0,1])

TypeError: 'numpy.ndarray' object is not callable

In [78]:
a1[[0,1],0:2]

array([[ 1.48523759,  0.13369167],
       [ 0.95077105, -0.23740909]])

In [79]:
a1

array([[ 1.48523759,  0.13369167,  1.40268948, -0.84208133],
       [ 0.95077105, -0.23740909, -2.42230403,  0.85819974],
       [-0.57275571, -0.7028063 ,  0.38544657,  0.33469914]])

In [87]:
a1[[1,2], 3:]

array([[0.85819974],
       [0.33469914]])

In [88]:
a1[[1,2], 3]

array([0.85819974, 0.33469914])

In [90]:
m1 = np.random.randint(1,3,(3,3))

In [91]:
m1

array([[2, 2, 2],
       [2, 2, 1],
       [1, 1, 1]])

In [92]:
m2 = np.random.randint(2,4,(3,3))

In [93]:
m2

array([[2, 2, 2],
       [3, 2, 3],
       [3, 3, 3]])

In [95]:
m1*m2  #this is a element wise multiplication and not a matrix multiplication

array([[4, 4, 4],
       [6, 4, 3],
       [3, 3, 3]])

In [96]:
m1@m2   #this is matrix multiplication

array([[16, 14, 16],
       [13, 11, 13],
       [ 8,  7,  8]])

In [97]:
#  @ is the symbol to do matrix multiplications

In [98]:
m1

array([[2, 2, 2],
       [2, 2, 1],
       [1, 1, 1]])

In [99]:
m2

array([[2, 2, 2],
       [3, 2, 3],
       [3, 3, 3]])

In [100]:
m1

array([[2, 2, 2],
       [2, 2, 1],
       [1, 1, 1]])

In [102]:
pow(m1,4)

array([[16, 16, 16],
       [16, 16,  1],
       [ 1,  1,  1]])

In [103]:
np.sqrt(m1)

array([[1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.        ],
       [1.        , 1.        , 1.        ]])

In [104]:
np.log10(m1)

array([[0.30103, 0.30103, 0.30103],
       [0.30103, 0.30103, 0.     ],
       [0.     , 0.     , 0.     ]])

In [105]:
np.exp(m1)

array([[7.3890561 , 7.3890561 , 7.3890561 ],
       [7.3890561 , 7.3890561 , 2.71828183],
       [2.71828183, 2.71828183, 2.71828183]])